name: Assign Roles

on:
  issue_comment:
    types: [ created ]

jobs:
  comment:
    if: contains(github.event.comment.body, 'assign roles')

    runs-on: [ self-hosted ]
    env:
      Comment: ${{ github.event.comment.body }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python3 -m pip install pandas tabulate
      - name: Test
        run: |
          python3 run.py
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.issue.number }}
          body-file: 'comment-body.md'
          reactions: 'heart'
          token: ${{ secrets.REPO_WORKFLOW_PAT }}

